---
services: docker

env:
  global:
    - DOCKER_USER: qwe1
    - DOCKER_IMAGE: docker-pelican
    - GITLAB_REG_URL: registry.gitlab.com
    - GITLAB_REG_USER: richardskumat
    - GITLAB_REG_IMAGE: docker-pelican
    - DOCKER_TLS_CERTDIR: ''
    - DOCKER_HOST: tcp://docker:2375/
  #matrix:
  #  - whatever

before_script:
  - docker info

script:
  # Run tests.
  - docker build -t $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_IMAGE .
  - docker images
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:travis-$DOCKER_IMAGE pelican --version
  # dockerhub
  - docker run --rm $DOCKER_USER/$DOCKER_IMAGE:latest pelican --version
  # gitlab
  - docker run $GITLAB_REG_URL/$GITLAB_REG_USER/$GITLAB_REG_IMAGE:latest pelican --version